### ISSUE TITLE
为啥不能上传QQ群？

### ISSUE THREAD

**Issue by kunpeng9** [BOOKXNOTE/BookxNote-pro#101]
![image](https://user-images.githubusercontent.com/44609485/99013547-b4dd0e80-258b-11eb-84b8-f0933fd5aca2.png)
如图；
显示提示安全检查未通过，禁止上传该文件；为啥腾讯软件中心下的软件不能上传QQ群？怎么回事？？？

**Comment by BOOKXNOTE** [comment]
不清楚，压缩为zip就可以吧

**Comment by kunpeng9** [comment]
> 不清楚，压缩为 zip 就可以吧
@BOOKXNOTE ；感谢；已解决；可以上传了；
