### ISSUE TITLE
同步及换电脑阅读问题

### ISSUE THREAD

**Issue by yangxuebabe** [BOOKXNOTE/BookxNote-pro#117]
1. 目前有同步功能吗？
2. 因为PDF和笔记是分离的，导致在另一台电脑上打开PDF时就没有笔记了。然后我把整个bookxnote的文件夹也拷贝过来，但似乎并不会自动匹配，再打开PDF仍然没有笔记。这个如何解决？只能在一台电脑上阅读吗？

**Comment by Maxine-X** [comment]
请问这个有解决吗~

**Comment by Michaeldbydbcl** [comment]
我之前也有同样问题，解决方法是用Dropbox，然后把BookXnote的文件夹所在path命名为完全一致，比如你家里电脑是c:dropbox\Bookxnote,办公室电脑的path也是c:dropbox\Bookxnote，软件只认路径，不会管你在哪个电脑打开的，当然这是非常笨拙的办法了。希望作者可以开发云同步。

**Comment by xiaoshanzhaguo** [comment]
> 我之前也有同样问题，解决方法是用Dropbox，然后把BookXnote的文件夹所在path命名为完全一致，比如你家里电脑是c:dropbox\Bookxnote,办公室电脑的path也是c:dropbox\Bookxnote，软件只认路径，不会管你在哪个电脑打开的，当然这是非常笨拙的办法了。希望作者可以开发云同步。

这个方法很好用，感谢你
