### ISSUE TITLE
【建议】脑图节点的巨大标题栏过于醒目，应该是没有字时令其宽度很小，类似MarginNote

### ISSUE THREAD

**Issue by Michaeldbydbcl** [BOOKXNOTE/BookxNote-pro#119]
如题，脑图的标题栏过于喧宾夺主，多数内容是不需要添加标题的，巨大的色块使得脑图主次不分，提取出的文字都被淹没在标题栏下面了。软件设计者把标题栏高度设定为字体高度，估计是为了方便双击直接添加文字，但是大多数提出来的内容是不需要标题的，应该是当添加文字到标题栏的时候，标题栏宽度才相应增大。

**Comment by BOOKXNOTE** [comment]
OK，我下个版本改进下。
