### ISSUE TITLE
标注直接添加到pdf中

### ISSUE THREAD

**Issue by Reveanime** [BOOKXNOTE/BookxNote-pro#13]
希望下划线，高亮等 PDF 标注中已有的标注能直接添加到 PDF 文件中，或者类似 xchangepdf 将标注展平到 PDF 也行

**Comment by BOOKXNOTE** [comment]
就是需要把笔记输出到原文PDF里面，这和我们现有设计冲突，比较难，后续再添加把笔记添加到原始PDF中进行导出。
