### ISSUE TITLE
【需求】希望pdf注释能与大纲能结合

### ISSUE THREAD

**Issue by Rdnj** [BOOKXNOTE/BookxNote-pro#170]
希望导入的大纲笔记能与导入的pdf注释相结合：
某条注释，放入对应范围的大纲条目下。

**Comment by M142857** [comment]
同建议。

**Comment by Rdnj** [comment]
将PDF文件的目录大纲及标注合并成一张思维导图的方法：

1. 打开BookxNote，将pdf文件导入。
2. 将目录导出到大纲笔记。操作步骤：点击目录图标右边的一个下三角型的符号，出现：目录导出为大纲笔记，点击。
3. 将注释导出到大纲笔记。点击软件左下角，内部包含三个点的一个圈图标，出现：导入PDF注释，点击
4. 大纲笔记重新组合排列。操作步骤：点击软件左侧最上面的“笔记大纲”图标，右键大纲笔记，点击“笔记重排”-“按文档目录分租重排”。
5. 导出导图文件。点击左侧的“笔记脑图”图标，将脑图导出即可，可以选择xmind格式。
