### ISSUE TITLE
需求：页面缩放和添加批注

### ISSUE THREAD

**Issue by GMN-git** [BOOKXNOTE/BookxNote-pro#36]

**Comment by BOOKXNOTE** [comment]
收到

**Comment by GMN-git** [comment]
> 关于页面缩放，软件页面占据屏幕一半的时候，如果进行120%的缩放页面没办法自动居中；希望可以设置软件在小屏幕进行缩放时，也可以保持居中，这样会更人性化；
> 第二个就是脑图文本节点进行文本批注时，当进入批注页面，添加多个批注时只能用鼠标点击上面的添加批注按钮，希望可以增加添加批注的快捷键，如Ctrl+enter之类的
> 第三就是开启节点编辑页面后，pdf主页面无法拖动，这样如果由跨页内容只能退出批注编辑页面，拖动到目的初，在进入节点编辑页面，显得有点繁琐，
> 希望楼主大大可以留意一下这些问题，做一下相应的优化，辛苦了！
