### ISSUE TITLE
朗读 中文发音

### ISSUE THREAD

**Issue by vincentteoh** [BOOKXNOTE/BookxNote-pro#38]
请问可以选择中文发音吗？因为朗读都是英文发音，无法阅读中文书籍。

**Comment by BOOKXNOTE** [comment]
需要安装中文语音包，或者安装了的，需要选择中文语音包
![image](https://user-images.githubusercontent.com/50521967/83227222-3c89b900-a1b6-11ea-9451-c08e9b25c2cf.png)

**Comment by vincentteoh** [comment]
可以了，谢谢您。
