### ISSUE TITLE
安装完成后的引导窗口无法完全显示使程序无法使用

### ISSUE THREAD

**Issue by albort11** [BOOKXNOTE/BookxNote-pro#97]
我是新用户，安装完成后，会出现一个引导窗口，设置默认目录等，但在我的多屏系统下（我是四个屏，win10系统），这个引导窗口不知为何出现在副屏角落，并且大部分在屏幕显示范围以外（即只能看到上边的一点图案，下面的文字和按钮显示不出来），而这个窗口不能拖动，并且锁住焦点，使设置目录的过程总过不去，造成用不了，后来我改了屏幕分辨率，使窗口能完全显示了，就通过了

最好这个引导窗口设置一下在主屏中心，并且可以拖动

**Comment by BOOKXNOTE** [comment]
这个问题我清楚了，已经修复了，下个版本发布。
