### ISSUE TITLE
数据导入到版本2

### ISSUE THREAD

**Issue by vincentteoh** [BOOKXNOTE/BookxNote-pro#98]
请问如何从版本1的数据导入到版本2？

**Comment by vincentteoh** [comment]
我知道如何导入了，一切很顺利。
只是在版本2，不能高亮英文字母，都是显示乱码������。

**Comment by vincentteoh** [comment]
不是全部文件都乱码，应该是我的文件问题。

**Comment by Zoe-20** [comment]
请问如何导入数据，点击导入后弹出导入成功但笔记中并没有出现。

**Comment by Zoe-20** [comment]
> 请问如何导入数据，点击导入后弹出导入成功但笔记中并没有出现。

已解决
因为旧版本中的书籍已改变位置，需重定向新位置
